version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "ci(deps): Update Actions: "
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps): "
      include: scope
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "build(deps): Update docker base image"
    schedule:
      interval: weekly
